### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by andyfaff** [DiamondLightSource/islatu#2]
The license and descriptions in setup.py need updating to reasonable values from:
```
    license='Closed source idk',
    description='An example package. Generated with cookiecutter-pylibrary.',
```

**Comment by RBrearton** [comment]
Thanks for pointing this out! I had fixed this a while ago on my local machine but for some (presumably git-black-magic-related) reason the updated setup.py never made it to github. I made a few other small adjustments to the setup.py file to make it less rubbish.
