### ISSUE TITLE
Missing software paper.md hosted in repository

### ISSUE THREAD

**Issue by daguiam** [DiamondLightSource/islatu#4]
A software `paper.md` must be hosted in the repository, as in the [JOSS submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements), but it is missing. 

Your paper should include:

- A list of the authors of the software and their affiliations, using the correct format.
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- A Statement of Need section that clearly illustrates the research purpose of the software.
- A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
- Acknowledgement of any financial support.

**Comment by RBrearton** [comment]
Hi there, the paper.md document is in the islatu_paper branch.
